### ISSUE TITLE
Map Text.file to be completed

### ISSUE THREAD

**Issue by jlou210** [jlou210/ZORK#1]
Work on it in your spare time, and plan out the map in one note first. It'll take a while to complete so just consistent but little work each day should do it.

Thank

**Comment by ambihaiakilan18** [comment]
Just finished adding descriptions to the first three worlds, will finish the rest soon. I finished the exits and room names according to the map for all of them, just need to add descriptions for the remaining

**Comment by ambihaiakilan18** [comment]
Just finished, it wouldn't commit but we got it to work - text files are finished, looks like something is wrong with the directions though
