### ISSUE TITLE
Directions in map - incorrect direction notation 

### ISSUE THREAD

**Issue by jlou210** [jlou210/ZORK#4]
When you travel through the map, you use the letters 'UE'. This is not necessary as we are not going up in most cases. Do not use UE. As well, do not use 'U' unless the player is travelling up stairs. You used 'U' when it should be 'N'. 
The player should be travelling N, E, S, W, U, D based on the compass directions, so the directions are fixed. 
Go through the map again and fix the exits in the text file.

**Comment by ambihaiakilan18** [comment]
What does P stand for?

**Comment by jlou210** [comment]
Sorry I meant 'D'. We can do NE or NW if you want but then you'd need to change that in the Rooms class where they recognize the letters.

**Comment by ambihaiakilan18** [comment]
all done, everything is committed. please check it over
