### ISSUE TITLE
Map directions

### ISSUE THREAD

**Issue by jlou210** [jlou210/ZORK#5]
In Arthur's world, it is impossible to go from Mr. Ratburn's Classroom to the study room, effectively sealing of Library off as well. Since Arthur's room and the study room are both north to the classroom, the program cannot tell which one to go to. So, split classroom into two rooms (Mr. Ratburn's Front Classroom, Mr. Ratburn's Back Classroom). This way if you go north, you are going north from different rooms.

As well, when going from the Backyardigan's Hallway to the House, you are going east. But to go back to the hallway from the house you are also going east. You should change this to go back to west.

Also, you used 'UE' in the Minigarden room (Backyardigans). Do not use this as it will mess up the code. Go room by room. There is no need to go 'UE'.

Finally, it seems you forgot to create a 'backyard' room (Backyardigans). Many of the rooms linked the the backyard room also do not work since this room does not exist.

**Comment by ambihaiakilan18** [comment]
So I looked through the code for Mr Ratburn's Classroom and I realized I changed the direction to the Study Room to NorthEast (P). 

I changed the Backyardigan's Hallway directions.

I changed the directions in the Room class a couple of days ago to from northeast (UE), northwest (UW), southeast (DE), and southwest (DW), to P, Q, R, and T respectively.

I created the backyard room and added the appropriate exit rooms as well.
