### ISSUE TITLE
Create entrance to treehouse on the map

### ISSUE THREAD

**Issue by jlou210** [jlou210/ZORK#6]

**Comment by ambihaiakilan18** [comment]
There is an entrance from the start point, the start point exits into the Main Room of the Treehouse and the Main Room goes back to the start point.

**Comment by jlou210** [comment]
I do not see this entrance in the code or the console. Can you try recommitting your work, because I do not even see this commit on the commit list on github.

**Comment by jlou210** [comment]
Can you try to recommit your code? I do not even see the changes you made on my code even when merging it, and on github it is not in the ‘commit’ section…
